### ISSUE TITLE
"Deauth" module never completes installation on nano

### ISSUE THREAD

**Issue by braco** [hak5/wifipineapple-modules#10]
Dependencies stay stuck at "Installing..." forever

Not sure how to debug yet.

**Comment by sundhaug92** [comment]
What kind of storage did you install it on?

**Comment by moliata** [comment]
@Foxtrot @sebkinne this issue should be closed as it's no longer relevant. The installation successfully completes, at least on the SD Card.

**Comment by sundhaug92** [comment]
@moliata It could be it fails under certain cases, though I do think this is this is more likely a support-case than a bug

**Comment by trashbo4t** [comment]
@braco ssh into your pineapple and run the dependencies script in /pineapple/modules/Deauth

Then you can see which line it fails on
