### ISSUE TITLE
-a flag added to reaver command in wps.run 

### ISSUE THREAD

**Issue by trashbo4t** [hak5/wifipineapple-modules#12]
> root@Pineapple:/sd/modules/wps/scripts# ./wps.sh start
>
> Reaver v1.6.3 WiFi Protected Setup Attack Tool
> Copyright (c) 2011, Tactical Network Solutions, Craig Heffner <cheffner@tacnetsol.com>
>
> reaver: invalid option -- a

ssh'd and ran wps.sh manually to discover this as output is not appearing in the wps module page logging.

**Comment by sebkinne** [comment]
cc @WhistleMaster

**Comment by WhistleMaster** [comment]
I'll have a look at it, thanks for the report !

**Comment by moliata** [comment]
@WhistleMaster is this still an issue?

**Comment by WhistleMaster** [comment]
@trashbo4t Can you post the options you chose and the content of /tmp/wps.run after you started the module ? I can't replicate the problem you had. Thanks.

**Comment by trashbo4t** [comment]
@WhistleMaster strange I cannot recreate this either after a factory reset and fresh install. 

Should probably move this to closed.

**Comment by WhistleMaster** [comment]
@sebkinne So I guess it can be closed then :)
