### ISSUE TITLE
SSLSplit - missing log folder on install

### ISSUE THREAD

**Issue by sopsmattw** [hak5/wifipineapple-modules#15]
The sslsplit start command fails because the log folder is missing from the package. 

Solution: root@Pineapple:~# mkdir /pineapple/modules/SSLsplit/log

<img width="1350" alt="screenshot 2018-03-09 16 53 56" src="https://user-images.githubusercontent.com/5041555/37235293-c3c6f2ce-23ba-11e8-9971-c82fd442784c.png">

**Comment by trashbo4t** [comment]
Opened a PR for this

**Comment by sebkinne** [comment]
Fixed in #18
