### ISSUE TITLE
can not install ngrep dependencies

### ISSUE THREAD

**Issue by huangwenweia** [hak5/wifipineapple-modules#31]
when i use opkg install ngrep , it told me this:
```
Unknown package 'ngrep'.
Collected errors:
 * opkg_install_cmd: Cannot install package ngrep.

```

**Comment by huangwenweia** [comment]
how can i solve this problem?

**Comment by Foxtrot** [comment]
It would appear that the ngrep ipk is not in the OpenWRT 15.05 repository (and doesn't seem to have been included in the previous releases 'new' packages).

You can install it by doing the following:

```
cd /tmp/
wget https://archive.openwrt.org/barrier_breaker/14.07/ar71xx/generic/packages/oldpackages/ngrep_1.45-3_ar71xx.ipk
opkg install ngrep_1.45-3_ar71xx.ipk
ln -s /usr/lib/libpcap.so.1 /usr/lib/libpcap.so.1.3
```

**Comment by trashbo4t** [comment]
Should this fix be added to the module in the case where it fails?

**Comment by huangwenweia** [comment]
@Foxtrot ok i will try it later

**Comment by huangwenweia** [comment]
@Foxtrot Fix it!!! , thank you!!!

**Comment by adde88** [comment]
I have a repo. full of useful tools for the Pineapples.
You can find the latest version of ngrep there, compiled with the "correct" version of libpcap, so you don't have to sym-link stuff to get it working.

Here's a link to ngrep from my repo:
https://raw.githubusercontent.com/adde88/openwrt-useful-tools/master/ngrep_1.45-3_ar71xx.ipk

**Comment by huangwenweia** [comment]
@adde88 Thanks guy , i will try it later

**Comment by adde88** [comment]
I've sent a pull-request to Hak5. Which would fix this problem.
But they could also decide to host the ngrep package on the hak5-repos. (that the pineapples are also using), which would fix the problem as well.

**Comment by huangwenweia** [comment]
@adde88 Nice

**Comment by moliata** [comment]
@Foxtrot @sebkinne https://github.com/hak5/wifipineapple-modules/pull/37#issue-209308795 should be pulled and then this issue should be closed.
