### ISSUE TITLE
Please update the version of Responder used in the Responder Module

### ISSUE THREAD

**Issue by chriscodinguk** [hak5/wifipineapple-modules#35]
Could you please update the version of Responder used by the Pineapple to the under support version at https://github.com/lgandx/Responder.

Specifically this includes the -P option which is far more effective at getting NTLMv2 hashes via WPAD (this is also the version that the Bash Bunny uses).

The dependencies are the same, and I have the lgandx version working fine on the Pineapple Nano

**Comment by adde88** [comment]
I've sent a PR to Hak5 that now uses this version of Responder. Good idea.

**Comment by WhistleMaster** [comment]
This has been addressed in https://github.com/hak5/wifipineapple-modules/pull/41
