### ISSUE TITLE
2.4 or 5ghz

### ISSUE THREAD

**Issue by SquirrelAssassin** [hak5/wifipineapple-modules#66]
so from the recon page I only see the 2.4 channels.  
from cli ... I see 5hz ... where is this is the ui?  

from cli I run airodump-ng --band abg wlan1mon and tada all the channels. 

**CH 54 ]**[ Elapsed: 24 s ][ 2019-07-17 14:32

 BSSID              PWR  Beacons    #Data, #/s  CH  MB   ENC  CIPHER AUTH ESSID

 00:2A:10:EB:96:BD   -1        0        0    0   5  -1                    <length:  0>
 00:2A:10:E4:61:FD   -1        0        0    0   6  -1                    <length:  0>

**Comment by Foxtrot** [comment]
Hi,

This repository is purposed solely for community WiFi Pineapple modules. Please do not post off-topic issues here. I suggest heading to https://forums.hak5.org/ instead.
