### ISSUE TITLE
OpenWRT 19.07 Module Dependency Issues

### ISSUE THREAD

**Issue by 3ndG4me** [hak5/wifipineapple-modules#74]
Not sure if it would be better to report individual package issues to OpenWRT or not, but I received an issue recently on my dev repo for OpenVPNConnect claiming some issues installing the dependencies for the module:

https://github.com/InjectionSoftwareDevelopment/OpenVPNConnect/issues/12

When I tried to reproduce this issue on a clean installation of the latest 2.6.1 WiFi Pineapple firmware I came across two interesting finds:

1. I was able to reproduce the issue verbatim, it appears that there is a kernel conflict with the OpenWRT 19.07 firmware's kernel 4.14 and the openvpn-mbedtls package.
2. When installing another module "Papers" it failed as well. Its dependencies were `zip` and `unzip`. `unzip` installed just fine, but `zip` did not exist.

I imagine this issue is affecting a few modules due to the firmware jump and what appears to be package support falling behind. In the case of OpenVPNConnect and Papers this totally breaks the modules on the 2.6.X pineapple firmware.

A solution in my case might be to bring my own openvpn installation, but that is going to require a significant module upgrade and is likely not a great idea as openvpn is no small application. I imagine for other modules such as Papers, we don't want to "roll" or "bring our own" zip package either.

Not sure what the best solution is here as this doesn't really seem like a fault of the WiFi Pineapple firmware itself, just good old package management lag. The answer might be to "just wait" for OpenWRT/opkg to get our packages out there.

Seeing as this significantly breaks some existing modules, I wanted to throw up an issue somewhere since there wasn't one already.

Would love some suggestions, I definitely don't mind contributing to a solution, just not sure what a good path would be (if anything).

**Comment by Foxtrot** [comment]
Hi,

Thanks for creating a PR for this. I'm looking into the issue with the openvpn-mbedtls (and other?) packages not installing due to the kernel mismatch.

**Comment by Foxtrot** [comment]
Hi,

Thanks again for reporting this issue. I'm happy to report that it's been solved.

```
root@Pineapple:~# opkg update
Downloading https://downloads.hak5.org/packages/mk6/1907/Packages.gz
Updated list of available packages in /var/opkg-lists/1907_pineapple
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/base/Packages.gz
Updated list of available packages in /var/opkg-lists/1907_base
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/1907_packages
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/1907_routing

root@Pineapple:~# opkg install openvpn-mbedtls
Installing openvpn-mbedtls (2.4.7-2) to root...
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/base/openvpn-mbedtls_2.4.7-2_mips_24kc.ipk
Installing kmod-tun (4.14.134-1) to root...
Downloading https://downloads.hak5.org/packages/mk6/1907/kmod-tun_4.14.134-1_mips_24kc.ipk
Installing liblzo2 (2.10-2) to root...
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/base/liblzo2_2.10-2_mips_24kc.ipk
Configuring kmod-tun.
Configuring liblzo2.
Configuring openvpn-mbedtls.
root@Pineapple:~# 
```

**Comment by 3ndG4me** [comment]
Thanks @Foxtrot ! I have verified this on my end as well and will report it back on my dev repo. Much appreciated!
