### ISSUE TITLE
tor module won't start 

### ISSUE THREAD

**Issue by arshiay** [hak5/wifipineapple-modules#86]
hi 
tor module won't start at all 
pineapple nano
V = 2.6.2

**Comment by catatonicprime** [comment]
This is a duplicate of [Issue 84](https://github.com/hak5/wifipineapple-modules/issues/84).

**Comment by arshiay** [comment]
hi
mine is not working on internal or sd 
please read carefully and then close issue closing issue not working

**Comment by catatonicprime** [comment]
@arshiay I just want to make sure you understand this issue was closed because it's a duplicate. More information will be available on the previously opened issue (link above).
